#!/bin/sh

git init --quiet

git add run-test
git commit --quiet -am "ci: add first file"

git add results
git commit --quiet -am "docs: add second file"
git tag 0.1.0

git add exp-stderr
git commit --quiet -am "fix: add third file

* test: append to path when running tests

- test: add auth file for post tests

* ci: add linting, macOS test, and linux test workflows

* feat: make sed commands more portable

* docs: add new ci badges to readme"

git add exp-stdout
git commit --quiet -am "test: add fourth file"

git remote add origin https://github.com/adamtabrams/change.git

change >act-stdout 2>act-stderr

rm -rf ./.git
