#!/bin/sh

git init --quiet

git add run-test
git commit --quiet -am "feat: add first file"
git add results
git commit --quiet -am "fix: add second file"
git tag 0.1.0

git add exp-stderr
git commit --quiet -am "fix: add third file"
git tag 0.1.1

git add exp-stdout
git commit --quiet -am "docs: add docs file"
git rm --quiet --cached exp-stdout
git commit --quiet -am "chore: remove chore file"

git add exp-stdout
git commit --quiet -am "build: add build file"
git rm --quiet --cached exp-stdout
git commit --quiet -am "ci: remove ci file"

git add exp-stdout
git commit --quiet -am "perf: add perf file"
git rm --quiet --cached exp-stdout
git commit --quiet -am "style: remove style file"

git add exp-stdout
git commit --quiet -am "test(md parser): add test file"
git rm --quiet --cached exp-stdout
git commit --quiet -am "feat(parser)!: remove feature file"

git add exp-stdout
git commit --quiet -am "fix!: add fix file"
git rm --quiet --cached exp-stdout
git commit --quiet -am "refactor!: remove refactor file"


git remote add origin https://github.com/adamtabrams/change.git

change >act-stdout 2>act-stderr

rm -rf ./.git
