#!/bin/sh

all_tests=$*
num_fails=0
num_tests=0
IFS="
"

[ $# = 0 ] && all_tests="./tests/*"
[ $# != 1 ] && echo "Running tests"

for test in $all_tests; do
    [ -f "$test" ] && continue
    num_tests=$((num_tests + 1))

    # Setup
    save_dir=$(pwd)
    cd "$test" || exit 1
    [ -d actual ] && rm -rf actual
    cp -r setup actual

    # Run
    cd actual || exit 1
    [ $# != 1 ] && echo
    basename "$test:"
    ./run-test

    # Results
    for line in $(./results); do
        echo "$line"
        new_fails=$(echo "$line" | grep -c "^[^ ]*FAIL")
        num_fails=$((num_fails + new_fails))
    done

    # Cleanup
    cd "$save_dir" || exit 1
done

echo
[ $# != 1 ] && echo "Total number of tests: $num_tests"
echo "Total number of failures: $num_fails"

[ $num_fails -gt 0 ] && exit 1
exit 0
