#!/bin/sh

git init --quiet

git add run-test
git commit --quiet -am "feat: add first file"
git add results
git commit --quiet -am "fix: add second file"
git tag 0.0.1

git add exp-stderr
git commit --quiet -am "fix: add third file"
git tag 0.0.2

git add exp-stdout
git commit --quiet -am "Fix add fourth file"
git tag 0.0.10

git remote add origin https://github.com/adamtabrams/change.git

change >act-stdout 2>act-stderr

rm -rf ./.git
