#!/bin/sh

git init --quiet

git add run-test
git commit --quiet -am "feat: add first file"
git add results
git commit --quiet -am "fix: add second file"
git tag "v0.1.0"

git add exp-stderr
git commit --quiet -am "feat: add third file"

git remote add origin https://github.com/adamtabrams/change.git

change tag >act-stdout 2>act-stderr

git tag --list >act-tags

rm -rf ./.git
