#!/bin/sh

git init --quiet

git add run-test
git commit --quiet -am "feat: add first file"
git add results
git commit --quiet -am "fix: add second file"
git tag 0.1.0

git add exp-stderr
git commit --quiet -am "add third file

more details

more plain text"
git tag 0.1.1

git add exp-stdout
git commit --quiet -am "add fourth file"
git rm --quiet --cached exp-stdout
git commit --quiet -am "fix: remove fourth file"

git remote add origin https://github.com/adamtabrams/change.git

change >act-stdout 2>act-stderr

rm -rf ./.git
