#!/bin/sh

git init --quiet

git add run-test
git commit --quiet -am "feat: add first file"
git add check-results
git commit --quiet -am "fix: add second file"
git tag "v0.0.1"

git add exp-stderr
git commit --quiet -am "feat: add third file"
git tag "v0.0.2"

git remote add origin https://github.com/adamtabrams/change.git

change >act-stdout 2>act-stderr

rm -rf ./.git
